#include<stdint.h>

// RESET & CLOCK CONTROL REGISTER
#define RCC_OFFSET 0x40023800UL

// AHB1 PERIPHERAL CLOCK ENABLE REGISTER
#define AHB1ENB_OFFSET 0X30
#define AHB1EB (*(volatile uint32_t*) (RCC_OFFSET+AHB1ENB_OFFSET)) 

// AHP2 PERIPHERAL CLOCK ENABLE REGISTER
#define APB2ENB_OFFSET 0X44
#define APB2ENB (*(volatile uint32_t*) (RCC_OFFSET+APB2ENB_OFFSET)) 

// GPIOA MODER REGISTER
#define GPIOA 0X40020000UL
#define GPIOA_MODER_OFFSET 0x00
#define GPIOA_MODER (*(volatile uint32_t*) (GPIOA+GPIOA_MODER_OFFSET))

// GPIOC MODER REGISTER
#define GPIOC 0X40020800UL
#define GPIOC_MODER_OFFSET 0x00
#define GPIOC_MODER (*(volatile uint32_t*) (GPIOC+GPIOC_MODER_OFFSET))

// GPIOA OUTPUT DATA REGISTER
#define GPIOA_ODR_OFFSET 0x14
#define GPIOA_ODR (*(volatile uint32_t*) (GPIOA+GPIOA_ODR_OFFSET))

// GPIOC INPUT DATA REGISTER
#define GPIOC_IDR_OFFSET 0x10
#define GPIOC_IDR (*(volatile uint32_t*) (GPIOC+GPIOC_IDR_OFFSET))

// GPIOA BIT SET/RESET REGISTER 
#define GPIOA_BSRR_OFFSET 0x18
#define GPIOA_BSRR (*(volatile uint32_t*) (GPIOA+GPIOA_BSRR_OFFSET))

// TIM1 
#define TIM1 0x40010000UL

// TIM1 COUNTER REGISTER
#define TIM1_CNT_OFFSET 0X24
#define TIM1_CNT (*(volatile uint32_t*) (TIM1+TIM1_CNT_OFFSET))

// TIM1 PRESCAL REGISTER
#define TIM1_PSC_OFFSET 0X28
#define TIM1_PSC (*(volatile uint32_t*) (TIM1+TIM1_PSC_OFFSET))

// TIM1 AUTO-RELOAD REGISTER 
#define TIM1_ARR_OFFSET 0X2C
#define TIM1_ARR (*(volatile uint32_t*) (TIM1+TIM1_ARR_OFFSET))

// TIM1 CONTROL REGISTER 1
#define TIM1_CR1_OFFSET 0X00
#define TIM1_CR1 (*(volatile uint32_t*) (TIM1+TIM1_CR1_OFFSET))

// TIM1 EVENT GENERATION REGISTER
#define TIM1_EGR_OFFSET 0X14
#define TIM1_EGR (*(volatile uint32_t*) (TIM1+TIM1_EGR_OFFSET))

// TIM1 STATUS REGISTER
#define TIM1_SR_OFFSET 0X10
#define TIM1_SR (*(volatile uint32_t*) (TIM1+TIM1_SR_OFFSET))


